### ISSUE TITLE
List does not work with Adaway or HostsMan

### ISSUE THREAD

**Issue by nimkip** [StevenBlack/hosts#188]
The following URL (https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts) is not able to be imported to HostsMan or Adaway apps. HostsMan returns the error "This source is not compatible. Server does not return all the necessary information." Adaway states "Online: Not Available".

**Comment by StevenBlack** [comment]
I'm not a Windows, nor an Android user.   I've had several discussions with folks at Adaway so I'm pretty sure we're not doing anything majorly wrong here.

 Does anyone have insight on this?

@nimkip this *might* be a hostsman bug...

**Comment by StevenBlack** [comment]
@nimkip see https://github.com/AdAway/AdAway/wiki/HostsSources -- this repo is listed there.

However it looks like this is an open bug in Adaway.  See https://github.com/AdAway/AdAway/issues/700

Maybe you could comment there and urge them into action?

You could always just clone this repo, and pull as needed prior to updating adaway from a local file.

**Comment by JasonD94** [comment]
This seems to be a bug with AdAway. It doesn't seem to show any GitHub URLs as being available. I've added my own hosts file for blocking Spotify ads and it does the same thing - "Local: not available, Online: not available".

However, since I've added my own hosts file I haven't gotten a single Spotify ad. So I'm willing to guess that it shows "not available" but can still access the hosts file and merge it. I've also noticed it shows the right number of sources applied, even if a few (such as the hosts file for this repo) show up as "not available" in the app.

**Comment by nimkip** [comment]
Good catch. Upon further inspection AdAway does indeed import the hosts correctly, even though the app says it does not. HostsMan on the other hand will not attempt to download the list.

**Comment by mistermarmot** [comment]
Just installed HostsMan and was looking for the best distribution and found yours to try out but ran into the same issue.
HostsMan seems to be looking for 'hosts.zip' instead of RAW so if you offer a zipped link on GitHub (like is [offered here](https://gist.github.com/msenturk/01df88c849f38fe685d4)) it might be all that is required for HostsMan to use your file.

**Comment by StevenBlack** [comment]
@nimkip @mistermarmot @JasonD94 the repo now contains `host.zip` files and should now work with HostMan and Adaway.  😎

**Comment by mistermarmot** [comment]
My initial assumption about the solution is wrong and HostsMan isn't using your HOSTS as a source yet.
HostsMan is looking for some handshaking information from the distribution server.

I'll create a post on their forums at http://forum.abelhadigital.com/index.php and see what they have to say about the requirements.  It would probably be resolved easily if you and their admin/coder/owner discuss it directly.

**Comment by Jezza-x3** [comment]
@StevenBlack it's still not letting it be used. It's something to do with GitHub I believe. Is there any way you could host it on another site similar to someonewhocares page?

**Comment by aequis** [comment]
This still isn't fixed. Why was this closed?

**Comment by StevenBlack** [comment]
Because it's not my bug.

**Comment by FadeMind** [comment]
HostsMan recognize line
```
fe80::1%lo0 localhost
```
as ERROR/CORRUPTED line. But infact this line is VALID IPv6 localhost for OSX system.

http://osxdaily.com/2014/04/12/restore-original-hosts-file-mac/


@StevenBlack @aequis @Jezza-x3

**Comment by Jezza-x3** [comment]
@StevenBlack If you could host it on a site such as someonewhocares host file, then it would let us download. HostsMan doesn't work with github. That's the main problem.
