### ISSUE TITLE
Entries break Waze app on Android

### ISSUE THREAD

**Issue by timkgh** [StevenBlack/hosts#760]
```
0.0.0.0 row-advil.waze.com
0.0.0.0 ads-resources.waze.com
0.0.0.0 ads-resources-legacy.waze.com
0.0.0.0 advil.waze.com
```
These entries seem to break the Waze app on Android. The app constantly displays "`Searching Network`" and when trying to access alternate routes it gives an error "`Uh-oh! Failed to communicate with routing server`"

**Comment by StevenBlack** [comment]
Ouch!  Thanks @timkgh

**Comment by StevenBlack** [comment]
Daniel @lightswitch05 can you please check this?  Waze is staggeringly useful...

**Comment by timkgh** [comment]
I should note this does not happen right away when you open the app but after the app is running for a few minutes or some other trigger.
Not sure whether all entries need to be removed or only some of them. Maybe Waze just got smart, if it detects it can't show ads it just claims there's no network.

**Comment by timkgh** [comment]
I will give it a try on a long drive today. Thanks for looking into it.

**Comment by StevenBlack** [comment]
This is fixed in [release 1.4.45](https://github.com/StevenBlack/hosts/releases).

Closing.

**Comment by timkgh** [comment]
Unfortunately the problem is not fixed, I still get the same issue though it takes a lot longer to trigger.
I use `AdAway` with the list `http://sbc.io/hosts/alternates/fakenews-gambling-porn/hosts` and the default 3 lists that come with AdAway.
If I disable just this list, Waze seems to work OK.
Here are the waze related entries in my `/etc/hosts` file:
```
$ grep waze /etc/hosts
127.0.0.1 row-advil.waze.com
::1 row-advil.waze.com
127.0.0.1 ads-resources-legacy.waze.com
::1 ads-resources-legacy.waze.com
127.0.0.1 ads-resources.waze.com
::1 ads-resources.waze.com
127.0.0.1 awazetribune.com
::1 awazetribune.com
```
(last 2 entires just match because of the grep but are not related, some fakenews site it seems)

Not sure whether it's one of the above or something else on the list that may be causing it. Maybe `row-advil.waze.com` needs to be removed too?

If I disable this list but leave the default AdAway lists enabled, all entries above are gone from /etc/hosts.

**Comment by lightswitch05** [comment]
I'll remove row-advil.waze.com later today. Any ideas on how to reproduce would be useful

**Comment by timkgh** [comment]
@lightswitch05 Thanks, didn't realize row-advil didn't come from your list.
Reproducing it is the tricky part as it doesn't happen right away, it takes a while to get into this state (I'm not even sure whether it's time or some other trigger like POI that causes it), but once it does, the only way to recover is to restart Waze.
I will try and whitelist `row-advil.waze.com` next but not sure when my next long drive is going to be.
This has been happening for the past couple of months but driving just around town I blamed it on spotty cell reception and on a buggy Waze app not being able to recover from it, but now I'm pretty sure it's the ad blocking it's not happy with. When Waze shows "Searching network" other apps have no problems getting data.

@StevenBlack can we please keep this issue open until we figure out which entries are the problem? Maybe others will be able to test too and chime in. Thanks.

**Comment by timkgh** [comment]
Whitelisting `row-advil.waze.com` seems to help, but I have yet to go on a long 3+ hr drive, only tested it on shorter drives. Can we talk to the maintainer of `someonewhocares` to remove it, please?

FWIW, there's another host I've seen mentioned in other threads where people are having similar problems `adsassets.waze.com`, but it does not seem to be on any lists here. It may just be that in the end we must allow ads in Waze to make it work reliably, which is not ideal but not horrible either, they don't bother you with ads during driving, they seem to pop up at stop lights.

**Comment by lightswitch05** [comment]
@timkgh the readme has hosts@someonewhocares.org as the best way to submit issues to that list maintainer

**Comment by timkgh** [comment]
I contacted hosts@someonewhocares.org and it's now removed from the list, if we could please refresh the list here too.

**Comment by StevenBlack** [comment]
Thanks @timkgh.  This is done, and is live and online in [release 1.4.46](https://github.com/StevenBlack/hosts/releases).

Closing!  Thanks everybody!

**Comment by timkgh** [comment]
For the record, there are still 2 entries left on the lightswitch05 list with waze.com domains:
```
0.0.0.0 ads-resources.waze.com
0.0.0.0 ads-resources-legacy.waze.com
```
I'll re-open the issue if they turn out to cause problems.

**Comment by timkgh** [comment]
Unfortunately Waze does not work reliably unless I add `*.waze.com` to the whitelist in AdAway. It seems that we cannot block anything in the waze.com domain. I propose we remove these 2 entries from the list:
```
ads-resources.waze.com
ads-resources-legacy.waze.com
```

**Comment by lightswitch05** [comment]
This is unfortunate. I’ll move them to a different list later today.

**Comment by lightswitch05** [comment]
Moved to my aggressive list - which is not in this project - via commit https://github.com/lightswitch05/hosts/commit/74e6160c5f5f55a9af54760b0abfbe7c0cf98446 . It should be removed in the next release. Thanks for keeping track of this and trying different options

**Comment by rajannpatel** [comment]
> @timkgh thanks for pointing out that it does not happen right away. It took me awhile to reproduce, but changing the destination several times triggered it. Whitelisting only `advil.waze.com` seems to have resolved the issue for me. I've already made the change to my list in [lightswitch05/hosts@4de8da8](https://github.com/lightswitch05/hosts/commit/4de8da8b2478bfd74dac273410c8583bc53c3d94) - please let me know if you continue having troubles after using the updated list

I am going to do some testing of my own and will report back what i find.
